# Generated by Django 2.2.7 on 2019-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateTime', models.CharField(max_length=50, verbose_name='时间')),
                ('Desc', models.CharField(max_length=50, verbose_name='描述')),
                ('Title', models.CharField(max_length=50, verbose_name='标题')),
                ('Url', models.CharField(max_length=50, verbose_name='链接')),
                ('approvalNum', models.CharField(max_length=50, verbose_name='点赞')),
                ('commentNum', models.CharField(max_length=50, verbose_name='评论')),
                ('hotDesc', models.CharField(max_length=50, verbose_name='热评')),
                ('idWeb', models.CharField(max_length=50, verbose_name='编号')),
                ('imgUrl', models.CharField(max_length=50, verbose_name='图片')),
            ],
        ),
    ]
