# Generated by Django 2.2.7 on 2019-12-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateTime', models.CharField(max_length=50, verbose_name='时间')),
                ('index', models.CharField(max_length=50, verbose_name='编号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('mark', models.CharField(max_length=50, verbose_name='热度')),
                ('level', models.CharField(max_length=50, verbose_name='等级')),
                ('link', models.CharField(max_length=50, verbose_name='链接')),
            ],
        ),
    ]
